resources:
- ../default
- ../samples
- bases/intel-tdx-dcap-operator.clusterserviceversion.yaml
- scc-role.yaml
- scc-rolebinding.yaml

patches:
- path: patches/qgs-env.yaml
  target:
    kind: Deployment
    name: intel-tdx-dcap-controller-manager
