version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    allow:
      - dependency-type: direct
    groups:
      kube-rs:
        patterns:
          - "kube"
          - "k8s-openapi"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /build/tdx-qgs
    schedule:
      interval: weekly
    groups:
      docker-tdx-qgs:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /build/operator
    schedule:
      interval: weekly
    groups:
      docker-operator:
        patterns:
          - "*"
