apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    app.kubernetes.io/name: intel-dcap-operator
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
