apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where the operator will be deployed
namespace: intel-dcap-operator-system

namePrefix: intel-tdx-dcap-

# Resources to include in the deployment
resources:
- ../crd
- ../rbac
- ../manager

# CommonLabels added to all resources
labels:
- pairs:
    app.kubernetes.io/part-of: intel-dcap-operator
