environments:
  default:
    values:
      - intelDevicePluginVersion: 0.37.0
      - nfdVersion: 0.19.0
      - dcapValuesFile: ./helmfile-qgs-values/tdx-qgs-online-values.yaml.gotmpl
---
repositories:
  - name: nfd
    url: https://kubernetes-sigs.github.io/node-feature-discovery/charts

helmDefaults:
  wait: true
  timeout: 600
  diffArgs:
    - --disable-validation
    - --disable-openapi-validation

releases:
  # --------------------------------------------------------------------------
  # Node Feature Discovery
  # --------------------------------------------------------------------------
  - name: nfd
    namespace: node-feature-discovery
    createNamespace: true
    chart: nfd/node-feature-discovery
    version: "{{ .Values.nfdVersion }}"
    hooks:
      - events: [ "postsync" ]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -k
          - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v{{ .Values.intelDevicePluginVersion }}
      - events: [ "postuninstall" ]
        showlogs: true
        command: kubectl
        args:
          - delete
          - -k
          - https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref=v{{ .Values.intelDevicePluginVersion }}

  # --------------------------------------------------------------------------
  # Intel TDX QGS
  # --------------------------------------------------------------------------
  - name: intel-tdx-qgs
    namespace: intel-dcap-operator-system
    createNamespace: true
    chart: ./intel-tdx-qgs
    needs:
      - node-feature-discovery/nfd
    values:
      - "{{ .Values.dcapValuesFile }}"
