{{- if and .Values.tdxQuoteGenerationService.enabled (eq .Values.tdxQuoteGenerationService.mode "Online") .Values.pcsApiKey.apiKey (not .Values.pcsApiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pcsApiKey.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "intel-tdx-qgs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.pcsApiKey.secretKey }}: {{ .Values.pcsApiKey.apiKey | quote }}
{{- end }}

