{{- if .Values.tdxQuoteGenerationService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-tdx-dcap-qgs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "intel-tdx-qgs.labels" . | nindent 4 }}
{{- end }}

